#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source ~/.bash_aliases

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export VISUAL="vim"
. /usr/lib/python3.7/site-packages/powerline/bindings/bash/powerline.sh
