#!/bin/bash
sleep 0.5
killall polybar
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload top > /dev/null 2>&1 &
    MONITOR=$m polybar --reload bottom > /dev/null 2>&1 & 
done
